[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography"]
description = """A crate for working with finite fields where the modulus is of unknown order,
typtical for RSA, Paillier, Hyperelliptic curves, etc.
"""
documentation = "https://docs.rs/unknown_order"
edition = "2018"
exclude = [
    "*.sh",
]
keywords = ["cryptography", "rsa", "bignum", "gmp", "security"]
license = "Apache-2.0"
name = "unknown_order"
readme = "README.md"
repository = "https://github.com/mikelodder7/unknown_order"
version = "0.1.4"

[features]
default = ["gmp"]
gmp = ["hex", "rand", "rust-gmp"]
rust = ["glass_pumpkin", "num-bigint", "num-integer", "num-traits", "rand"]

[dependencies]
digest = "0.9"
glass_pumpkin = { version = "1.0.0", optional = true }
hex = { version = "0.4", optional = true }
num-bigint = { version = "0.4", optional = true }
num-integer = { version = "0.1", optional = true }
num-traits = { version = "0.2", optional = true }
openssl = { version = "0.10.34", optional = true }
rand = { version = "0.8", optional = true }
rust-gmp = { version = "0.5", optional = true }
serde = { version = "1.0", features = ["serde_derive"] }
zeroize = "1.3"

[dev-dependencies]
blake2 = "0.9"
multibase = "0.9"
serde_json = "1.0"
